services:
  claude:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: claude

    working_dir: /workspace

    volumes:
      - /home/laidq/.local/data:/workspace

    stdin_open: true
    tty: true

